name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 8
          check-latest: true
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk8
          arguments: build --no-build-cache
          gradle-version: wrapper
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: liquidbounce
          path: build/libs/liquidbounce-*.jar
